<?
  $limitList = $this->params->getLimitList();
  $currentURL = $this->currentURL();

  list($filters, $currentURL) = $this->portalPages()->getArrayOfFilters($currentURL);
?>
<? if (count($limitList) > 1): ?>
  <form class="form-inline" action="<?= $currentURL ?>" method="get">
    <label class='dropdown-select-label'>
      <select id="limit"
              name="limit"
              class="jumpMenu form-control dropdown-select ajax-update-limit">
        <? foreach ($limitList as $limitVal => $limitData):
          $limitData['selected'] = ($limitVal == $this->limit) ? true : false;
          ?>
          <option value="<?= $this->escapeHtmlAttr($limitVal) ?>"<?= $limitData['selected'] ? ' selected="selected"' : '' ?>>
            <?= $this->escapeHtml($limitData['desc'].' '.$this->translate('records-in-genitive')) ?>
          </option>
        <? endforeach; ?>
      </select>
    </label>
    <? foreach ($filters as $filter): ?>
      <input type="hidden" name="<?= key($filter) ?>" value="<?= current($filter) ?>" />
    <? endforeach; ?>
    <noscript><input type="submit" value="<?= $this->transEsc("Set") ?>" /></noscript>
  </form>
<? endif; ?>
