<?php
$addThis = $this->addThis();

if (!empty($addThis)) {
  $this->headScript()->appendFile('https://s7.addthis.com/js/250/addthis_widget.js?pub=' . urlencode($addThis));
}

// Set up some variables for convenience:
$id = $this->driver->getUniqueId();
$controllerClass = 'controller:' . $this->record($this->driver)->getController();
$cart = $this->cart();
$cartId = $this->driver->getResourceSource() . '|' . $id;

$handleOfflineFavorites = ! $this->isLoggedIn && $this->offlineFavoritesEnabled;

$source = explode(".", $id)[0];

$this->jsTranslations()->addStrings([
    'previousRecordText' => "<?=$this->translate('Switch to previous record')?>",
    'nextRecordText'     => "<?=$this->translate('Switch to next record')?>",
    'recordText'         => "<?=$this->translate('record')?>",
]);

?>
<ul class="list-group record-toolbar">
  <li class="list-group-item">
  <?php if ($this->referer): ?>
    <div id="records-switching" data-record_id="<?=$id?>" data-record_referer="<?=$this->referer?>"></div>
  <?php endif?>
  </li>

  <?php if(method_exists($this->driver, "getRecordType") && $this->driver->getRecordType() != "library"): ?>
    <li class="list-group-item">
      <a id="mail-record" class="modal-link <?=$controllerClass?>" title="<?=$this->transEsc('Email this')?>" rel="nofollow">
        <? $titleHtml = "<i class=\"pr-communication-emailenvelopemail\"> </i>" . $this->transEsc('Email this') ?>
        <?= $this->help()->getElementHelp('element_help_email_this', $titleHtml) ?>
      </a>
    </li>

    <?php $exportFormats = $this->export()->getFormatsForRecord($this->driver); ?>
    <?php if(count($exportFormats) > 0): ?>
      <li class="dropdown list-group-item">
        <a class="export-toggle dropdown-toggle" data-toggle="dropdown" href="<?=$this->recordLink()->getActionUrl($this->driver, 'Export')?>" rel="nofollow">
          <?php $titleHtml = "<i class=\"pr-web-uploadarrow\"> </i>" . $this->transEsc('Export Record') ?>
          <?= $this->help()->getElementHelp('element_help_export_record', $titleHtml) ?>
        </a>
        <ul class="dropdown-menu record-export" role="menu">
          <li><a href="https://www.citacepro.com/nacist-dokument-sysno/<?=$this->driver->getUniqueID()?>?katalog=cpk" title="CitacePRO" target="_blank">CitacePRO</a></li>
          <?php foreach ($exportFormats as $exportFormat): ?>
            <li><a <? if ($this->export()->needsRedirect($exportFormat)): ?>target="<?=$this->escapeHtmlAttr($exportFormat)?>Main" <? endif; ?>href="<?=$this->recordLink()->getActionUrl($this->driver, 'Export')?>?style=<?=$this->escapeHtmlAttr($exportFormat)?>" rel="nofollow"><?=$this->transEsc($this->export()->getLabelForFormat($exportFormat))?></a></li>
          <?php endforeach?>
        </ul>
      </li>
    <?php endif?>
  <?php endif?>
  <li class="list-group-item" id='permalinkItem'>
    <a class="modal-link" id='permalinkAnchor' title="<?=$this->translate('Permalink')?>" >
      <i class="pr-web-linkurl"> </i> <?=$this->translate('Permalink')?>
    </a>
  </li>

  <?php if(method_exists($this->driver, "getRecordType") && $this->driver->getRecordType() != "library"): ?>
    <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
      <li class="list-group-item"><?php
        $linkHref  = ($handleOfflineFavorites) ? '#' : $this->recordLink()->getActionUrl($this->driver, 'Save');
        $addTitle  = $this->transEsc('Add to favorites');
        $remTitle  = $this->transEsc('remove_from_favorites');

      ?><a id="save-record" class="modal-link <?=$controllerClass?>" href="<?=$linkHref?>" title="<?=$addTitle?>" rel="nofollow">
          <i class="pr-interface-favoritestar"> </i>
          <span class="add-favorite-link"><?=$addTitle?></span>
          <span class="remove-favorite-link" hidden><b><?=$remTitle?></b></span>
        </a>
      </li>
    <?php endif?>
  <?php endif?>
  <?php if(! (($this->driver instanceof CPK\RecordDriver\SolrAuthority) || ($controllerClass == 'controller:Edsrecord') || ($this->driver->getRecordType() == "library") )): ?>
  <li class="list-group-item" id='citace-pro'>
    <a class="modal-link disabled-link" title="<?=$this->transEsc('Show citations')?>" ><i class="pr-communication-bubblechattalkconversationline"> </i> <?=$this->transEsc('Show citations')?></a>
    <i id='citation-link-spinner' class="fa fa-spinner fa-spin"></i>
  </li>
  <?php endif?>
    <?php if($controllerClass == 'controller:Edsrecord'): ?>
        <?php $customLinks = array_merge($this->driver->getFTCustomLinks(), $this->driver->getCustomLinks());
        if (!empty($customLinks)): ?>
            <?php foreach ($customLinks as $customLink):
                $url = isset($customLink['Url']) ? $customLink['Url'] : '';
                $mot = isset($customLink['MouseOverText'])? $customLink['MouseOverText'] : '';
                $icon = isset ($customLink['Icon']) ? $customLink['Icon'] : '';
                $name = isset($customLink['Text']) ? $customLink['Text'] : '';

                ?><li class="list-group-item">
                    <a href="<?=$this->escapeHtmlAttr($url)?>" target="_blank" title="<?=$this->escapeHtmlAttr($mot)?>" class="custom-link">
                      <i class="pr-web-linkurl"> </i><?=$this->translate($this->escapeHtml($name))?>
                    </a>
                </li>
            <?php endforeach?>
        <?php endif?>
    <?php endif?>
  <li class="list-group-item" id='shareItem'>
    <a class="modal-link" id='shareAnchor' title="<?=$this->translate('Share this')?>" >
      <i class="pr-web-sharenetwork"> </i> <?=$this->translate('Share this')?>
    </a>
  </li>
  <?php if (!empty($addThis)): ?>
    <li><a class="addThis addthis_button list-group-item" href="https://www.addthis.com/bookmark.php?v=250&amp;pub=<?=urlencode($addThis)?>"><i class="fa fa-fw fa-bookmark"></i> <?=$this->transEsc('Bookmark')?></a></li>
  <?php endif?>
  <?php if ($cart->isActive()): ?>
    <li id="bookbag-menu"  class="list-group-item">
      <input id="cartId" type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($cartId)?>" />
      <a id="cart-add" class="<? if(!$cart->contains($cartId)): ?>correct <? endif ?>hidden" href="#"><i class="fa fa-fw fa-plus"></i> <?=$this->transEsc('Add to Book Bag') ?></a>
      <a id="cart-remove" class="<? if($cart->contains($cartId)): ?>correct <? endif ?>hidden" href="#"><i class="fa fa-fw fa-minus-circle"></i> <?=$this->transEsc('Remove from Book Bag') ?></a>
      <noscript>
        <form method="post" name="addForm" action="<?=$this->url('cart-home')?>">
          <input type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($cartId)?>" />
          <?php if ($cart->contains($cartId)): ?>
            <input class="btn btn-default" type="submit" name="delete" value="<?=$this->transEsc('Remove from Book Bag')?>"/>
          <?php else: ?>
            <input class="btn btn-default" type="submit" name="add" value="<?=$this->transEsc('Add to Book Bag')?>"/>
          <?php endif?>
        </form>
      </noscript>
    </li>
  <?php endif?>
</ul>