  <div class="col-md-4 widget">
    <div class='header'>
      <? if ($this->widget->getShowAllRecordsLink()): $filter = specialUrlEncode(\LZCompressor\LZString::compressToBase64('inspiration:"'.$this->widget->getName().'"')); ?>
        <a href='/Search/Results?lookFor0[]=&type0[]=AllFields&bool0[]=AND&join=AND&searchTypeTemplate=basic&page=1&keepEnabledFilters=true&limit=<?=$this->layout()->limit?>&sort=<?=$this->layout()->sort?>&filter=<?=$filter?>' title='<?=$this->translate('Show all')?>' style='color: #000;'>
          <h2><?=$this->translate($this->widget->getName())?></h2>
        </a>
      <? else: ?>
        <h2><?=$this->translate($this->widget->getName())?></h2>
      <? endif; ?>

    </div>
    <div class="list-group">
      <? foreach ($this->widget->getContents() as $item): $id = $this->record($item->getRecordDriver())->getRelevantRecord($item->getValue()); $isAuthority = ($item->getRecordDriver() instanceof \CPK\RecordDriver\SolrAuthority); ?>
      <a href="/Record/<?=$id?>" class="list-group-item clearfix"">
        <div class='row'>
          <? if ($this->widget->getShowCover()): ?>
              <?
              $recordId =  preg_replace("/\./", "", $id);
              $recordId =  preg_replace("/:/", "", $recordId);
              $formats = $item->getRecordDriver()->getFormats();
              ?>
              <div class="col-xs-3 col-sm-2 col-md-3 cover_<?=$recordId?>" id="<?=$recordId?>">
                <?php if ($bibinfo = $this->record($item->getRecordDriver())->getObalkyKnihJSONV3()): ?>
                  <?php if ($isAuthority): ?>
                  <div
                      data-obalkyknihcz="displayAuthorityCover"
                      data-advert="<?=htmlspecialchars( $item->getRecordDriver()->getPersonalName(), ENT_QUOTES )?>"
                      data-bibinfo="<?=htmlspecialchars( $bibinfo, ENT_QUOTES )?>"
                      data-recordId="<?=$recordId?>"
                      data-format="<?= (! empty($formats[0]) ? $this->record($item->getRecordDriver())->getFormatClass($formats[0]) : 'authority-unknown') ?>">
                  </div>
                  <?php else: ?>
                  <div
                      data-obalkyknihcz="displayCover"
                      data-advert="<?=htmlspecialchars( $item->getRecordDriver()->getTitle(), ENT_QUOTES )?>"
                      data-bibinfo="<?=htmlspecialchars( $bibinfo, ENT_QUOTES )?>"
                      data-recordId="<?=$recordId?>"
                      data-format="<?= (! empty($formats[0]) ? $this->record($item->getRecordDriver())->getFormatClass($formats[0]) : 'unknown') ?>">
                  </div>
                  <?php endif; ?>
                <? endif;?>

                <div class="iconlabel">
                  <? if (! empty($formats)): ?>
                    <i class="cover-pr-icon-medium pr-format-<?= $this->record($item->getRecordDriver())->getFormatClass($formats[0]) ?>"></i>
                  <? else: ?>
                    <i class="cover-pr-icon-medium pr-format-<?= $isAuthority ? 'authority-unknown' : 'unknown' ?>"></i>
                  <? endif; ?>
                </div>

              </div>
              <div class="col-xs-9 col-sm-10 col-md-9 content">
          <? else: ?>
              <div class="col-xs-12 content">
          <? endif; ?>
            <h4 class="list-group-item-heading">
              <?= $isAuthority ? $item->getRecordDriver()->getPersonalName() : $item->getRecordDriver()->getTitle() ?>
            </h4>
            <p class="list-group-item-text">
              <? if ($this->widget->getDescription() == 'author'): ?>
                <?= $item->getRecordDriver()->getDeduplicatedAuthors()['main'] ?>
              <? elseif ($this->widget->getDescription() == 'description'): ?>
                <?= ($this->language == 'cs') ? $item->getDescriptionCs() : $item->getDescriptionEn() ?>
              <? endif; ?>
            </p>
          </div>
        </div>
      </a>
      <? endforeach; ?>
      <? if ($this->widget->getShowAllRecordsLink()): $filter = specialUrlEncode(\LZCompressor\LZString::compressToBase64('inspiration:"'.$this->widget->getName().'"')); ?>
      <a href='/Search/Results?lookFor0[]=&type0[]=AllFields&bool0[]=AND&join=AND&searchTypeTemplate=basic&page=1&keepEnabledFilters=true&limit=<?=$this->layout()->limit?>&sort=<?=$this->layout()->sort?>&filter=<?=$filter?>' class="list-group-item clearfix" title='<?=$this->translate('Show all')?>'>
        <div class='row more-info'>
          <div class='col-xs-10'>
            <?=$this->translate('Show all')?>
          </div>
          <div class='col-xs-2' style='text-align: right;'>
            <i class="pr-interface-arrowright"></i>
          </div>
        </div>
      </a>
      <? endif; ?>
    </div>
  </div>