<!-- Modal -->
<div class='modal fade' id='exportFavoritesModal' tabindex='-1' role='dialog' aria-labelledby='exportFavoritesLabel'>
  <div class='modal-dialog' role='document'>
    <div class='modal-content'>
      <form>
          <div id='export-ids-container'>
          </div>
          <div class='modal-header'>
            <button type='button' class='close' data-dismiss='modal' aria-label='Close'>
              <span aria-hidden='true'>&times;</span>
            </button>
            <h4 class='modal-title' id='exportFavoritesLabel'><?=$this->translate('Export Favorites')?></h4>
          </div>
          <div class='modal-body'>

            <div class='form-group'>
              <label class='control-label' for='exportFormat'><?=$this->translate('Format') ?></label>
              <select class='form-control' id='favorites-export-options'>
              </select>
            </div>

            <div id='favorites-export-file-container'>
            </div>

          </div>
          <div class='modal-footer'>
            <input type='button'
                   class='btn btn-primary'
                   onclick='VuFind.exportOfflineFavorites()'
                   value='<?=$this->translate('Export')?>'>
          </div>
      </form>
    </div>
  </div>
</div>