<?
  // Set page title.
  $this->headTitle($this->translate('Conspectus'));

  // Set up breadcrumbs:
  if (isset($this->overrideTitle)) {
    $this->layout()->breadcrumbs .= '<li class="active">'.$this->escapeHtml($this->overrideTitle).'</li>';
  } else {
    $this->layout()->breadcrumbs .= '<li class="active">'.$this->transEsc('Conspectus').': '.$this->escapeHtml($lookfor).'</li>';
  }

  $sortedList = $this->sortFacetList($this->results, $this->field, $this->facets[$this->field]['list'], 'search-results');
?>
<div class="<?= $this->layoutClass('mainbody') ?> results">
  <h2><?= $this->transEsc('Conspectus') ?></h2>
  <p>
    <? foreach ($sortedList as $url => $value): ?>
      <li><a href="<?= $url ?>"
             title="<?= $this->escapeHtml($value) ?>"><?= $this->escapeHtml($value) ?>
        </a>
      </li>
    <? endforeach; ?>
  </p>
</div>
