<? if ($this->user): ?>
  <? if ($this->user->getLibraryCards()->count() > 1): ?>
    <form class='form-inline' action='<?=$this->url('librarycards-selectcard')?>' method='get'>
      <label for='library_card'>
        <?=$this->transEsc('Library Card')?>
      </label>
      <select id='library_card' name='cardID' class='jumpMenu form-control'>
        <? foreach ($this->user->getLibraryCards() as $card): ?>
          <?
            $target = '';
            $username = $card->cat_username;
            if (strstr($username, '.')) {
              list($target, $username) = explode('.', $username, 2);
            }
          ?>
          <option value='<?=$this->escapeHtmlAttr($card->id)?>'
                  <?=$card->cat_username == $this->user->cat_username ? ' selected="selected"' : ''?>>
            <?=$this->transEsc($card->card_name ?? $card->cat_username) ?>
            <? if ($target): ?>
              (<?=$this->transEsc("source_$target", null, $target)?>)
            <? endif; ?>
          </option>
        <? endforeach; ?>
      </select>
      <noscript><input type='submit' class='btn btn-default' value='<?=$this->transEsc('Set')?>'></noscript>
    </form>
  <? endif; ?>
<? endif; ?>
