<?php
// Set page title.
$this->headTitle($this->translate('configurations_approval'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li><a title="' . $this->transEsc('Main page') . '" href="/Search">' . $this->transEsc('Main page') . '</a></li> ' .
    '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'.
    '<li class="active"><a href="/Admin/ConfigurationsApproval">'.$this->transEsc('configurations_approval').'</a></li> ';
$this->layout()->title = $this->translate('configurations_approval');
$this->layout()->templateName = 'configurations/approval';
$hasRequests = false;
?>
<div class="row clearfix">
  <ul class="breadcrumb hidden-print"><?=$this->layout()->breadcrumbs?></ul>
  <div class="col-sm-3">
    <?=$this->render("admin/menu.phtml")?>
  </div>
  <div class="col-sm-9 well">
    <h2><?=$this->transEsc('configurations_approval')?></h2>
    <?=$this->flashmessages() ?>
    <?php
    foreach($configs as $source => $config):
      $transRequested = $config['requested'];
      $transActive = $config['active'];

      $isAleph = isset($transRequested['Catalog']['dlfport']);

      $template = $isAleph ? $alephTemplate : $ncipTemplate;

      $defs = $template['Definitions'];
      unset($template['Definitions']);

      $hidden = $defs['hidden'];

      // These two cannot be changed by anyone - they're generated
      unset($transRequested['IdResolver']['prefix']);
      unset($transRequested['Catalog']['requester']);

      if (! empty($transRequested)):
        $hasRequests = true;
    ?>
    <div class="well">
      <form action="/Admin/ConfigurationsApproval" method="POST">
        <table id="configurationsApprovalTable" class="table table-striped col-sm-12">
          <thead>
            <tr>
              <td colspan="2">
                <h3>
                  <?=$this->transEsc('source_' . $source)?>
                  <img class="pull-right" src="<?=$this->logos()->getLogo($source)?>" height="32">
                </h3>
              </td>
            </tr>
          </thead>
          <tbody id="configurationsApprovalTableTbody">
            <?php
            foreach($transRequested as $section => $keys):
              if(! empty($keys) && array_search($section, $hidden) === false):
            ?>
            <tr><td colspan="2"><b>[<?=$section?>]</b></td></tr>
            <?php
            foreach($keys as $key => $value):
              if (array_search($section . ':' . $key, $hidden) === false):
                $isChanged  = isset($transActive[$section][$key]) && $value != $transActive[$section][$key];
                $isRequired = ! in_array($section . ':' . $key, $defs['optional']);
                $isCheckbox = $defs[$section][$key] === 'checkbox';
                $itsValue   = $isChanged ? $transActive[$section][$key] : '';
                $itsLabel   = $this->transEsc($template[$section][$key]);
                $checkValue = function( $val ) {
                    return ( strtolower( $val ) === 'on' || intval( $val ) === 1) ? '1' : '0';
                };

                // Fix for checkboxes ("on" vs "1" :/)
                if ($isCheckbox) {
                    $itsValue  = $checkValue( $itsValue );
                    $isChanged = ( $checkValue( $value ) !== $itsValue );
                }
            ?>
            <tr title="<?=($isRequired ? $this->transEsc('This field is required') . ' - ' : '')  . $itsLabel?>">
              <td class="col-sm-3"><?=$key . (($isRequired) ? ' *' : '')?></td>
              <td class="col-sm-9 approval-conf-edit-col">
                <div><?=
                  ($isChanged)
                      ? ((!empty($itsValue))
                            ? '<del style="color: red">' . $itsValue . '</del><br>'
                            : ''
                        ) . '<ins style="color: green">' . $value . '</ins>'
                      : $value
                ?></div>
                <?=sprintf(
                  '<input class="form-control hidden" value="%1$s" type="%2$s" placeholder="%3$s" title="%3$s" name="%4$s"%5$s%6$s>',
                  $value,
                  $defs[$section][$key],
                  $itsLabel,
                  $section . '[' . $key . ']',
                  ($isCheckbox && $value) ? ' checked="checked"' : '',
                  ($isRequired) ? ' required="required"' : ''
                )?>
              </td>
            </tr>
            <?php endif; endforeach; ?>
          <?php endif; endforeach; ?>
          </tbody>
        </table>
        <textarea class="col-sm-12" name="message" placeholder="<?=$this->transEsc('approval_description')?>" title="<?=$this->transEsc('approval_description')?>"></textarea>
        <div class="btn-group">
          <input id="configurationsApprovalTableSubmit" class="btn btn-primary" type="submit" name="approved" value="<?=$this->transEsc('approve_config_change') ?>">
          <input class="btn btn-primary" type="submit" name="denied" value="<?=$this->transEsc('deny_config_change') ?>" formnovalidate>
        </div>
        <input type="hidden" name="source" value="<?=$source?>">
      </form>
    </div>
    <?php endif; endforeach;

    // If there are no requests
    if (!$hasRequests): ?>
    <div class="well"><?=$this->transEsc('approve_no_requests')?></div>
    <?php endif;?>
  </div>
</div>