<li id="notificationsDropdown" class="dropdown">
  <a style="display: none;" href="#" class="dropdown-toggle" data-toggle="dropdown" id="notif_icon">
    <i style="font-size: 20px;" class="pr-web-warningwarnalert"></i>
  </a>
  <ul id="notificationsList" class="dropdown-menu">
    <li>
      <div class="notif-header"> <?=$this->translate('source_cpk', null, 'Knihovny.cz')?>
        <i class="pull-right icon-logo-komplet notif-knihovny-logo"></i>
      </div>
      <div id="notif_synchronous_notifications" <?=$this->globalNotifications()->isEnabled() || !$user ? '' : 'hidden="hidden"'?>>
        <?=$this->globalNotifications()->renderAll()?>
      </div>
      <div id="notif_loader" class="notif-default" hidden="hidden">
        <i class="fa fa-spinner fa-spin"></i>
        <span class="label label-info"><?=$this->transEsc('Loading')?> ...</span>
      </div>
      <div id="notificationsListDiv" class="notif-list-div"><?php/* Here will be rendered notifications from CPK.notifications */?></div>
    </li>
    <?php
    if ($user):
      foreach ($libraryCards as $libraryCard):
        $source = explode('.', $libraryCard->cat_username)[0];
    ?>
    <li data-institution="<?=$source?>.parent" data-source="<?=$source?>" data-username="<?=$libraryCard->cat_username?>" id="<?=$source?>" class="institutionNotificationsLi">
      <div class="notif-header"> <?=$this->translate('source_' . $source, null, $source)?>
        <img height="20" class="pull-right" src="<?=$this->logos()->getLogo($source)?>">
        <div id="notificationsListLoader_<?=$libraryCard->cat_username?>" data-institution="<?=$source?>" class="notif-default">
          <i class="fa fa-spinner fa-spin"></i>
          <span class="label label-info"><?=$this->transEsc('Loading')?> ...</span>
        </div>
      </div>
      <div id="notificationsListDiv_<?=$libraryCard->cat_username?>" class="notif-list-div institution-notif-list-div"><?php/* Here will be rendered notifications from CPK.notifications */?></div>
    </li>
    <?php endforeach; endif;?>
  </ul>
</li>