<? if ($this->pageCount): ?>
  <ul class="pagination">
    <!-- Previous page link -->
    <? if (isset($this->previous)): ?>
      <li>
        <? $newParams = $this->params; $newParams['page'] = $this->previous; ?>
        <a href="<?= $this->currentPath() . '?' . http_build_query($newParams); ?>"
           title="<?=$this->translate('Previous')?>">
          &laquo; <?=$this->translate('Previous')?>
        </a>
      </li>
    <? else: ?>
      <li class="disabled">
        <span>&laquo; <?=$this->translate('Previous')?></span>
      </li>
    <? endif; ?>

    <!-- First page link -->
    <? if (isset($this->first) && $this->first != $this->current): ?>
      <li>
        <? $newParams = $this->params; $newParams['page'] = $this->first; ?>
        <a href="<?= $this->currentPath() . '?' . http_build_query($newParams); ?>"
           title="<?=$this->translate('First')?>">
          <?=$this->translate('First')?>
        </a>
      </li>
    <? else: ?>
      <li class="disabled">
        <span><?=$this->translate('First')?></span>
      </li>
    <? endif; ?>

    <!-- Numbered page links -->
    <? foreach ($this->pagesInRange as $page): ?>
      <? if ($page != $this->current): ?>
        <li>
          <? $newParams = $this->params; $newParams['page'] = $page; ?>
          <a href="<?= $this->currentPath() . '?' . http_build_query($newParams); ?>"
             title="<?=$page?>">
            <?=$page?>
          </a>
        </li>
      <? else: ?>
        <li class="active">
          <span><?=$page?></span>
        </li>
      <? endif; ?>
    <? endforeach; ?>

    <!-- Last page link -->
    <? if (isset($this->last)  && $this->last != $this->current): ?>
      <li>
        <? $newParams = $this->params; $newParams['page'] = $this->last; ?>
        <a href="<?= $this->currentPath() . '?' . http_build_query($newParams); ?>"
           title="<?=$this->translate('Last')?>">
          <?=$this->translate('Last')?>
        </a>
      </li>
    <? else: ?>
      <li class="disabled">
        <span><?=$this->translate('Last')?></span>
      </li>
    <? endif; ?>

    <!-- Next page link -->
    <? if (isset($this->next)): ?>
      <li>
        <? $newParams = $this->params; $newParams['page'] = $this->next; ?>
        <a href="<?= $this->currentPath() . '?' . http_build_query($newParams); ?>"
           title="<?=$this->translate('Next')?> >">
          <?=$this->translate('Next')?> >
        </a>
      </li>
    <? else: ?>
      <li class="disabled"> <span><?=$this->translate('Next')?> &raquo;</span>
    <? endif; ?>
  </ul>
<? endif; ?>
