<?
  // Set page title.
  $this->headTitle($this->driver->getBreadcrumb());
?>

<!-- Sigla -->
<? if ($sigla = $this->driver->getSigla()): ?>
  <h2>
    <i class='pr-interface-circlerighttrue'></i>
    <?=$this->translate('Sigla')?>
  </h2>
  <p><?=$this->escapeHtml($sigla)?></p>
<? endif; ?>

<!-- LastUpdated -->
<? if ($lastUpdated = $this->driver->getLastUpdated()): ?>
  <h2>
    <i class='pr-interface-circlerighttrue'></i>
    <?=$this->translate('LastUpdated')?>
  </h2>
  <p><?=$this->escapeHtml($lastUpdated)?></p>
<? endif; ?>

