<?
  // Set page title.
  $this->headTitle($this->translate('Description') . ': ' . $this->driver->getBreadcrumb());

  // Grab clean ISBN for convenience:
  $isbn = $this->driver->getCleanISBN();
?>
<table class='table table-striped' summary='<?=$this->transEsc('Description')?>'>
  <? if ($summ = $this->driver->getSummary()): ?>
    <? $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Summary')?>: </th>
      <td>
        <? foreach ($summ as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>

  <? if ($dateSpan = $this->driver->getDateSpan()): ?>
    <? $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Published')?>: </th>
      <td>
        <? foreach ($dateSpan as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>

  <? if ($notes = $this->driver->getGeneralNotes()): ?>
    <? $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Item Description')?>: </th>
      <td>
        <? foreach ($notes as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>

  <? if ($physical = $this->driver->getPhysicalDescriptions()): ?>
    <? $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Physical Description')?>: </th>
      <td>
        <? foreach ($physical as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>

  <? if ($freq = $this->driver->getPublicationFrequency()): ?>
    <? $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Publication Frequency')?>: </th>
      <td>
        <? foreach ($freq as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>

  <? if ($playTime = $this->driver->getPlayingTimes()): ?>
    <? $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Playing Time')?>: </th>
      <td>
        <? foreach ($playTime as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>

  <? if ($system = $this->driver->getSystemDetails()): ?>
    <? $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Format')?>: </th>
      <td>
        <? foreach ($system as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>

  <? if ($audience = $this->driver->getTargetAudienceNotes()): ?>
    <? $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Audience')?>: </th>
      <td>
        <? foreach ($audience as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>

  <? if ($awards = $this->driver->getAwards()): ?>
    <? $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Awards')?>: </th>
      <td>
        <? foreach ($awards as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>

  <? if ($credits = $this->driver->getProductionCredits()): ?>
    <? $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Production Credits')?>: </th>
      <td>
        <? foreach ($credits as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>

  <? if ($bib = $this->driver->getBibliographyNotes()): ?>
    <? $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Bibliography')?>: </th>
      <td>
        <? foreach ($bib as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>

  <? if ($isbns = $this->driver->getISBNs()): ?>
    <? $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('ISBN')?>: </th>
      <td>
        <? foreach ($isbns as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>

  <? if ($issns = $this->driver->getISSNs()): ?>
    <? $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('ISSN')?>: </th>
      <td>
        <? foreach ($issns as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>

  <? if ($doi = $this->driver->tryMethod('getCleanDOI')): ?>
    <? $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('DOI')?>: </th>
      <td><?=$this->escapeHtml($doi)?></td>
    </tr>
  <? endif; ?>

  <? if ($related = $this->driver->getRelationshipNotes()): ?>
    <? $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Related Items')?>: </th>
      <td>
        <? foreach ($related as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>

  <? if ($access = $this->driver->getAccessRestrictions()): ?>
    <? $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Access')?>: </th>
      <td>
        <? foreach ($access as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>

  <? if ($findingAids = $this->driver->getFindingAids()): ?>
    <? $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Finding Aid')?>: </th>
      <td>
        <? foreach ($findingAids as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>

  <? if ($publicationPlaces = $this->driver->getHierarchicalPlaceNames()): ?>
    <? $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Publication_Place')?>: </th>
      <td>
        <? foreach ($publicationPlaces as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>

  <? if ($authorNotes = $this->authorNotes($isbn || [])): ?>
    <? $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Author Notes')?>: </th>
      <td>
        <? foreach ($authorNotes as $provider => $list): ?>
          <? foreach ($list as $field): ?>
            <?=$field['Content']?><br/>
          <? endforeach; ?>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>

  <? if (! $contentDisplayed): // Avoid errors if there were no rows above ?>
    <tr><td><?=$this->transEsc('no_description')?></td></tr>
  <? endif; ?>
</table>
