<?
  // Set page title.
  $this->headTitle($this->driver->getBreadcrumb());
  $this->headScript()->appendFile('jquery-ui.min.js');
  $this->headScript()->appendFile('ajax-record-tabs.js');
  $this->headScript()->appendFile('eds-availability-tab.js');

  $issns = $this->driver->getIssns();
  $electronicIssns = $this->driver->getElectronicIssns();
  $isbns = $this->driver->getIsbns();
  $publishDate = $this->driver->getPublishDate();
  $titles = $this->driver->getTitles();
  $authors = $this->driver->getAuthors();
  $sourceTitle = $this->driver->getSourceTitle();
  $volume = $this->driver->getVolume();
  $accessUrl = $this->driver->getAccessUrl();
  $containsFulltext = $this->driver->containsFulltext();
?>

<div class='list-group'>
  <div id='eds-links'>
    <div id='only-one-eds-link-header' class='d-none'>
      <div class='mb-5'><?= $this->help()->getQuestionMarkHelp('eds-links-found') ?></div>
      <h3><?= $this->translate('Fulltext is avalable for users of this institution') ?>:</h3>
    </div>
    <div id='many-eds-links-header' class='d-none'>
      <div class='mb-5'><?= $this->help()->getQuestionMarkHelp('eds-links-found') ?></div>
      <h3><?= $this->translate('Fulltext is avalable for users of these institutions') ?>:</h3>
    </div>
    <div id='free-eds-link-available' class='d-none'>
      <div class='mb-5'><?= $this->help()->getQuestionMarkHelp('eds-links-found') ?></div>
      <h3><?= $this->translate('Fulltext is free') ?></h3>
    </div>

    <table class='table table-striped'>
      <tbody>
        <div id='eds-links-placeholder'>
          <div id='no-eds-links' class='d-none mb-5'>
          <?= $this->help()->getQuestionMarkHelp('eds-links-not-found') ?></div>
        </div>
      </tbody>
    </table>
  </div>

  <script>
      let $_data = {
          accessUrl: <?= $accessUrl ? '"'.$accessUrl.'"' : 'undefined' ?>,
          containsFulltext: <?= $containsFulltext ? '"'.$containsFulltext.'"' : 'undefined' ?>,
          issns: <?= $issns ? '"'.implode(", ", $issns).'"' : 'undefined' ?>,
          electronicIssns: <?= $electronicIssns ? '"'.implode(", ", $electronicIssns).'"' : 'undefined' ?>,
          isbns: <?= $isbns ? '"'.implode(", ", $isbns).'"' : 'undefined' ?>,
          publishDate: <?= $publishDate ? '"'.$publishDate.'"' : 'undefined' ?>,
          titles: <?= $titles ? '"'.implode(", ", $titles).'"' : 'undefined' ?>,
          authors: <?= $authors ? '"'.implode(", ", $authors).'"' : 'undefined' ?>,
          sourceTitle: <?= $sourceTitle ? '"'.$sourceTitle.'"' : 'undefined' ?>,
          volume: <?= $volume ? '"'.$volume.'"' : 'undefined' ?>,
      };
      handleEdsAvailability($_data);
  </script>

</div>
