<?
$limitList = $this->params->getLimitList();
$list      = $this->params->getSortList();
?>

<? if ( ! empty($list)): ?>
  <div class="dropdown" id="limit-container">
    <button class="btn btn-default dropdown-toggle ajax-update-limit"
            type="button"
            id="dropdownMenu1"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="true">
      <span><?= $this->translate('View')." " ?></span>
      <span class='value'>
          <? foreach ($limitList as $limitVal => $limitData): ?>
              <? if ($limitVal == $this->limit): ?>
                  <?= $limitVal ?>
              <? endif; ?>
          <? endforeach; ?>
      </span>
      <span><?= " ".$this->translate('per page') ?></span>
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
        <? foreach ($limitList as $limitVal => $limitData): ?>
          <li>
            <a href="#"
               class='apply-limit'
               data-limit='<?= $limitVal ?>'
               title='<?= $this->translate('Limit To') ?>'><?= $limitVal ?>
            </a>
          </li>
        <? endforeach; ?>
    </ul>
  </div>
<? endif; ?>
