<script>
    dataLayer.push({
        'page': {
            'category': 'account'
        }
    });
</script>
<div class='profile-menu'>
  <h3><?=$this->transEsc('Your Account')?></h3>
  <ul class='list-group'>
    <? $user = $this->auth()->isLoggedIn(); if ($user['home_library'] !== 'Dummy'): ?>
      <? if ('ils-none' !== $this->ils()->getOfflineMode()): ?>
        <a href='<?=$this->url('myresearch-checkedout')?>' class='list-group-item clearfix<?=$this->active == 'checkedout' ? ' active' : ''?>'>
          <?=$this->transEsc('Checked Out Items')?>
          <span class='pull-right flip profile-menu-item-icon hidden-xs-down'><i class='pr-document-bookpaper'></i></span>
        </a>
        <a href='<?=$this->url('myresearch-checkedouthistory')?>' class='list-group-item clearfix<?=$this->active == 'checkedouthistory' ? ' active' : ''?>'>
          <?=$this->transEsc('Checked Out History')?>
          <span class='pull-right flip profile-menu-item-icon hidden-xs-down'><i class='pr-document-bookpaper'></i></span>
        </a>
        <a href='<?=$this->url('myresearch-holds')?>' class='list-group-item clearfix<?=$this->active == 'holds' ? ' active' : ''?>'>
          <?=$this->transEsc('Holds and Recalls')?>
          <span class='pull-right flip profile-menu-item-icon hidden-xs-down'><i class='pr-time-clockhour'></i></span>
        </a>
        <? if ($this->ils()->checkFunction('StorageRetrievalRequests')): ?>
          <a href='<?=$this->url('myresearch-storageretrievalrequests')?>' class='list-group-item clearfix<?=$this->active == 'storageRetrievalRequests' ? ' active' : ''?>'>
      <?=$this->transEsc('Storage Retrieval Requests')?>
      <span class='pull-right flip profile-menu-item-icon hidden-xs-down'><i class='fa fa-archive'></i></span>
          </a>
        <? endif; ?>
        <a href='<?=$this->url('myresearch-fines')?>' class='list-group-item clearfix<?=$this->active == 'fines' ? ' active' : ''?>'>
          <?=$this->transEsc('Fines and Charges')?>
          <span class='pull-right flip profile-menu-item-icon hidden-xs-down'><i class='pr-ecommerce-creditcardmastercard'></i></span>
        </a>
        <a href='<?=$this->url('myresearch-profile')?>' class='list-group-item clearfix<?=$this->active == 'profile' ? ' active' : ''?>'>
            <? $titleHtml = $this->transEsc('Profile'); ?>
              <?= $this->help()->getElementHelp('element_help_profile', $titleHtml) ?>
              <span class='pull-right flip profile-menu-item-icon hidden-xs-down'><i class='pr-user-single'></i></span>
        </a>
        <a href='<?=$this->url('myresearch-settings')?>' class='list-group-item clearfix<?=$this->active == 'settings' ? ' active' : ''?>'>
          <?=$this->transEsc('Settings')?>
          <span class='pull-right flip profile-menu-item-icon hidden-xs-down'><i class='pr-setting-wrench'></i></span>
        </a>
        <? if ($user->isAdmin()): ?>
          <a href='<?=$this->url('admin')?>' class='list-group-item clearfix<?=$this->active == 'admin' ? ' active' : ''?>'>
            <?=$this->transEsc('Administration')?>
            <span class='pull-right flip profile-menu-item-icon hidden-xs-down'><i class='pr-setting-gear2'></i></span>
          </a>
        <? endif; ?>
        <? if (! empty($user['major'])): ?>
          <a href='<?=$this->url('statistics-dashboard')?>' class='list-group-item clearfix<?=$this->active == 'statistics' ? ' active' : ''?>'>
            <?=$this->transEsc('Statistics')?>
            <span class='pull-right flip profile-menu-item-icon hidden-xs-down'><i class='pr-web-trafficstatisticgraph2'></i></span>
          </a>
        <? endif; ?>

      <? endif; ?>
    <? endif; ?>
    <? if ($user && $user->libraryCardsEnabled()): ?>
      <a href='<?=$this->url('librarycards-home')?>' class='list-group-item clearfix<?=$this->active == 'librarycards' ? ' active' : ''?>'>
          <? $titleHtml = $this->transEsc('Linked accounts'); ?>
          <?= $this->help()->getElementHelp('element_help_linked_accounts', $titleHtml) ?>
        <span class='pull-right flip profile-menu-item-icon hidden-xs-down'><i class='pr-user-malegroup'></i></span>
      </a>
    <? endif; ?>
    <? if ($this->accountCapabilities()->getSavedSearchSetting() === 'enabled'): ?>
      <a href='<?=$this->url('search-history')?>?require_login' class='list-group-item clearfix<?=$this->active == 'history' ? ' active' : ''?>'>
        <?=$this->transEsc('history_saved_searches')?>
        <span class='pull-right flip profile-menu-item-icon hidden-xs-down'><i class='pr-interface-searchtickdone'></i></span>
      </a>
    <? endif; ?>
    <? if ($user): ?>
      <a href='<?=$this->url('myresearch-logout')?>' class='list-group-item clearfix'>
        <?=$this->transEsc('Log Out')?>
        <span class='pull-right flip profile-menu-item-icon hidden-xs-down'><i class='pr-interface-logoutexit'></i></span>
      </a>
    <? endif; ?>
  </ul>
  <? if ($this->auth()->isLoggedIn() && $this->auth()->getManager()->supportsPasswordChange()): ?>
    <h4><?=$this->transEsc('Preferences')?></h4>
    <ul class='list-group'>
      <a href='<?=$this->url('myresearch-changepassword') ?>' class='list-group-item clearfix<?=$this->active == 'newpassword' ? ' active' : ''?>'>
        <?=$this->transEsc('Change Password') ?>
        <span class='pull-right flip profile-menu-item-icon hidden-xs-down'><i class='pr-user-passwordlock2'></i></span>
      </a>
    </ul>
  <? endif; ?>
  <? if ($this->userlist()->getMode() !== 'disabled' && $user = $this->auth()->isLoggedIn()): ?>
    <div class='profile-menu-divider'></div>
    <ul class='list-group'>
      <a href='<?=$this->url('myresearch-favorites')?>' class='list-group-item clearfix<?=$this->active == 'favorites' ? ' active' : ''?>'>
        <?=$this->transEsc('Your Favorites')?>
        <span class='pull-right flip profile-menu-item-icon hidden-xs-down'><i class='pr-interface-favoritestar2'></i></span>
      </a>
      <? $lists = $user->getLists() ?>
      <div class='profile-favorites-list'>
      <? foreach ($lists as $list): ?>
          <a href='<?=$this->url('userList', array('id' => $list['id']))?>' class='list-group-item clearfix<?=$this->active == 'list' . $list['id'] ? ' active' : ''?>'>
            <?=$this->escapeHtml($list['title'])?>
            <span class='badge'><?=$list->cnt?></span>
          </a>
      <? endforeach; ?>

      <div class='profile-menu-divider'></div>

      <a href='<?=$this->url('editList', array('id'=>'NEW'))?>' title='<?=$this->transEsc('Create a List') ?>' class='list-group-item clearfix'>
        <?=$this->transEsc('Create a List') ?>
        <span class='pull-right flip profile-menu-item-icon hidden-xs-down'><i class='pr-interface-plusadd'></i></span>
      </a>
      </div>
    </ul>
  <? endif ?>
</div>