<?
  // Set up page title:
  $this->headTitle($this->translate('Favorites'));
  $this->headScript()->appendFile('offlineFavorites.js');
?>
<div class='row'>
  <div>

    <div class='clearfix hidden-print'>
  	  <h2 class='pull-left flip'><?=$this->transEsc('Favorites')?></h2>
    </div>

		<div class='favorites-list-header'>
      <div id='favorites-list-header-content' class='hidden'>

        <div class='pull-left select-all-favorites'>
          <input type='checkbox' onclick='selectAllFavorites(this);'>
          <?=$this->translate('Select all favorites')?> | <?=$this->translate('Selected favorites')?>
        </div>

        <div class='pull-right flip'>
          <div class='dropdown'>
            <button class='btn btn-default dropdown-toggle ajax-update-sort'
                    type='button'
                    id='offline-favorites-sort'
                    data-toggle='dropdown'
                    aria-haspopup='true'
                    aria-expanded='true'>
              <span><?=$this->translate('Sort').' '?></span>
              <span class='value'>
                  <?=$this->translate($sortData['desc']);?>
              </span>
              <span class='caret'></span>
            </button>
            <ul class='dropdown-menu' aria-labelledby='offline-favorites-sort'>
              <li><a><?=$this->transEsc('By Recent')?></a></li>
              <li><a><?=$this->transEsc('By Author')?></a></li>
              <li><a><?=$this->transEsc('sort_title')?></a></li>
            </ul>
          </div>
        </div>

        <div class='favorites-list-actions'>
          <a href='#' onclick='deleteSelectedFavorites();'><?=$this->transEsc('Delete')?></a> |
          <a href='#' onclick='emailSelectedFavorites();'><?=$this->transEsc('email_selected')?></a> |
          <a href='#' onclick='exportSelectedFavorites();'><?=$this->transEsc('export_selected')?></a> |
          <a href='#' onclick='printSelectedFavorites();'><?=$this->transEsc('print_selected')?></a>
        </div>
      </div>
		</div>



    <div>
      <div id='offline-favorites-container'>
      </div>
    </div>
  </div>

</div>