<?
  // Set up page title:
  $this->headTitle($this->translate('Favorites'));
  $this->headScript()->appendFile('offlineFavorites.js');
?>
<div class='row'>
  <div>

    <div class='clearfix hidden-print'>
  	  <h2 class='pull-left flip'><?=$this->transEsc('Favorites')?></h2>
    </div>

		<div class='favorites-list-header'>
      <div id='favorites-list-header-content' class='hidden'>

        <div class='pull-left select-all-favorites'>
          <input type='checkbox' onclick='selectAllFavorites(this);'>
          <?=$this->translate('Select all favorites')?> | <?=$this->translate('Selected favorites')?>
        </div>

        <div class='pull-right flip'>
          <div class='dropdown favorites-sort-dropdown'>
            <button class='btn btn-default dropdown-toggle ajax-update-sort'
                    type='button'
                    id='offline-favorites-sort'
                    data-toggle='dropdown'
                    aria-haspopup='true'
                    aria-expanded='true'>
              <span><?=$this->translate('Sort').' '?></span>
              <span class='value' id='sort-favorites-by-param-container'>
                  <?=$this->translate('By addition time');?>
              </span>
              <span class='caret'></span>
            </button>
            <ul class='dropdown-menu' aria-labelledby='offline-favorites-sort'>
              <li><a onclick='VuFind.sortOfflineFavoritesBy("created")'><?=$this->transEsc('By addition time')?></a></li>
              <li><a onclick='VuFind.sortOfflineFavoritesBy("author")'><?=$this->transEsc('By Author')?></a></li>
              <li><a onclick='VuFind.sortOfflineFavoritesBy("title")'><?=$this->transEsc('By Title')?></a></li>
            </ul>
          </div>
        </div>

        <div class='favorites-list-actions'>
          <a onclick='deleteSelectedFavorites();'><?=$this->transEsc('Delete')?></a> |
          <a onclick='emailSelectedFavorites();'><?=$this->transEsc('email_selected')?></a> |
          <a onclick='showExportFavoritesModal();'><?=$this->transEsc('export_selected')?></a> |
          <a onclick='printSelectedFavorites();'><?=$this->transEsc('print_selected')?></a>
        </div>

        <?=$this->render('favorites/my-profile/export-modal.phtml')?>
        <?=$this->render('favorites/my-profile/send-email-modal.phtml')?>
      </div>
		</div>

    <div>
      <div id='offline-favorites-container'>
      </div>
    </div>
  </div>

</div>