<a title='<?= $this->translate('Add to favorites') ?>'
   id='add-record-<?=$this->driver->getRecordIdHash()?>-to-favorites'
   rel='nofollow'
   data-recordId='<?=$this->driver->getUniqueID()?>'
   class='add-record-to-favorites-link <?= in_array($this->driver->getUniqueID(), $this->favorites) ? 'hidden' : '' ?>'
    <?= $this->isLoggedIn  ? 'data-toggle="modal"' : '' ?>
    <?= $this->isLoggedIn  ? 'onclick="VuFind.openFavoriteRecordModal(\''.$this->driver->getUniqueID().'\', \''
        . htmlspecialchars($this->driver->getTitle()) . '\')"' : '' ?>
    <?= !$this->isLoggedIn
        ? 'onclick="VuFind.addToFavorites(
          \''.$this->driver->getUniqueID().'\',
          false,
          \''.$this->searchClassId.'\'
        )"'
        : '' ?>>
    <i class='pr-interface-favoritestar'> </i>
  <span>
    <?=$this->translate('Add to favorites')?>
  </span>
</a>

<a title='<?= $this->translate('Remove from favorites') ?>'
   id='remove-record-<?=$this->driver->getRecordIdHash()?>-from-favorites'
   rel='nofollow'
   data-recordId='<?=$this->driver->getUniqueID()?>'
   class='font-bold remove-record-from-favorites-link <?= !in_array($this->driver->getUniqueID(), $this->favorites)
       ? 'hidden'
       : '' ?>'
   onclick='VuFind.removeFromFavorites("<?=$this->driver->getUniqueID()?>", "<?=$this->searchClassId?>")'>
  <i class='pr-interface-favoritestar'> </i>
  <span>
    <?=$this->translate('Remove from favorites')?>
  </span>
</a>