<!-- Add record to favorites Modal -->
<div class='modal fade favoriteModalForRecord'
     id='favoriteModalForRecord<?=$this->driver->getRecordIdHash()?>'
     tabindex='-1'
     role='dialog'
     aria-labelledby='favoriteModalForRecord<?=$this->driver->getRecordIdHash()?>Label'
     aria-hidden='true'>
  <div class='modal-dialog' role='document'>
    <div class='modal-content'>
      <div class='modal-header'>
        <h5 class='modal-title' id='favoriteModalForRecord<?=$this->driver->getRecordIdHash()?>Label'>
          <?= $this->translate('add_favorite_prefix') ?>
          <span class='title-in-heading' id='favoriteModalForRecord<?=$this->driver->getRecordIdHash()?>Title'>
          </span>
          <?= $this->translate('add_favorite_suffix') ?>
        </h5>
        <button type='button' class='close' data-dismiss='modal' aria-label='Close'>
          <span aria-hidden='true'>&times;</span>
        </button>
      </div>
      <div class='modal-body'>
        <div class='form-group'>
          <label for='favoritesListFor<?=$this->driver->getRecordIdHash()?>'>
              <?=$this->translate('Choose a List') ?>
          </label>
          <? if (! empty($this->favoritesLists)): ?>
            <select id='favoritesListFor<?=$this->driver->getRecordIdHash()?>'
                    class='control-label form-control select2Select'>
              <? foreach ($this->favoritesLists as $list): ?>
                <option value='<?=$list['id']?>'>
                  <?=htmlspecialchars($list['title'])?>
                </option>
              <? endforeach; ?>
            </select>
          <? endif; ?>
        </div>

        <div>
          <a class='btn btn-link'
             id='create-favorite-list'
             href='<?= "/MyResearch/EditList/NEW?"
                  . "recordId=" . $this->driver->getUniqueId()
                  . "&recordSource=" . $this->searchClassId ?>'
             title='<?= empty($this->favoritesLists)
                 ? $this->translate('Create a List')
                 : $this->translate('or create a new list') ?>'>
            <?= empty($this->favoritesLists)
                ? $this->translate('Create a List')
                : $this->translate('or create a new list') ?>
          </a>
        </div>

        <? if (! empty($this->favoritesLists)): ?>
          <br>
          <div class='form-group'>
            <label class='control-label' for='favoritesListFor<?=$this->driver->getRecordIdHash()?>Note'>
              <?=$this->translate('Add a Note') ?>
            </label>
            <textarea class='form-control' id='favoritesListFor<?=$this->driver->getRecordIdHash()?>Note'>
            </textarea>
          </div>
        <? endif; ?>
      </div>
      <div class='modal-footer'>
        <button type='button'
                class='btn btn-primary'
                data-dismiss='modal'
                onclick='VuFind.addToFavorites(
                    "<?=$this->driver->getUniqueID()?>",
                    true,
                    {searchClassId: "<?=$this->searchClassId?>"}
                )'>
          <?= $this->translate('Add to favorites'); ?>
        </button>
      </div>
    </div>
  </div>
</div>