<!-- Add record to favorites Modal -->
<div class='modal fade favoriteModalForRecord'
     id='favoriteModalForRecord<?=$this->driver->getRecordIdHash()?>'
     tabindex='-1'
     role='dialog'
     aria-labelledby='favoriteModalForRecord<?=$this->driver->getRecordIdHash()?>Label'
     aria-hidden='true'>
  <div class='modal-dialog' role='document'>
    <div class='modal-content'>
      <div class='modal-header'>
        <h5 class='modal-title' id='favoriteModalForRecord<?=$this->driver->getRecordIdHash()?>Label'>
          <?= $this->translate('add_favorite_prefix') ?>
          <span class='title-in-heading' id='favoriteModalForRecord<?=$this->driver->getRecordIdHash()?>Title'>
          </span>
          <?= $this->translate('add_favorite_suffix') ?>
        </h5>
        <button type='button' class='close' data-dismiss='modal' aria-label='Close'>
          <span aria-hidden='true'>&times;</span>
        </button>
      </div>
      <div class='modal-body'>

        <ul class="nav nav-tabs nav-justified">
          <li class="active">
            <a data-toggle="tab" href="#favorites-lists-tab">
              <?=$this->transEsc('Existing list') ?>
            </a>
          </li>
          <li><a data-toggle="tab" href="#favorites-new-list-tab"><?=$this->transEsc('New list') ?></a></li>
        </ul>

        <div class="tab-content">
          <div id="favorites-lists-tab" class="tab-pane fade in active">
            <div class='form-group'>
              <label for='favoritesListFor<?=$this->driver->getRecordIdHash()?>'>
                <?=$this->translate('Choose a List') ?>
              </label>
              <div id='favoritesListsModalPlaceholderFor<?=$this->driver->getRecordIdHash()?>'></div>
            </div>
          </div>
          <div id="favorites-new-list-tab" class="tab-pane fade">
            <div class='form-group'>
              <label for='favoritesListFor<?=$this->driver->getRecordIdHash()?>'>
                <?=$this->translate('Favorites list title') ?>
              </label>
              <input type='text'
                     class='form-control'
                     id='newFavoritesListFor<?=$this->driver->getRecordIdHash()?>Title'>
              <label class='control-label' for='newFavoritesListFor<?=$this->driver->getRecordIdHash()?>Description'>
                <?=$this->translate('Favorties list description') ?>
              </label>
              <textarea class='form-control'
                        id='newFavoritesListFor<?=$this->driver->getRecordIdHash()?>Description'></textarea>
            </div>
          </div>
        </div>

        <label class='control-label' for='favoritesListFor<?=$this->driver->getRecordIdHash()?>Note'>
          <?=$this->translate('Favorite record note') ?>
        </label>
        <textarea class='form-control' id='favoritesListFor<?=$this->driver->getRecordIdHash()?>Note'></textarea>

      </div>
      <div class='modal-footer'>
        <button type='button'
                class='btn btn-primary'
                data-dismiss='modal'
                onclick='VuFind.addToFavorites(
                    "<?=$this->driver->getUniqueID()?>",
                    true,
                    {searchClassId: "<?=$this->searchClassId?>"}
                )'>
          <?= $this->translate('Add to favorites'); ?>
        </button>
      </div>
    </div>
  </div>
</div>