<? if ($visFacets = $this->recommend->getVisFacets()): ?>
  <? /* load jQuery flot */
    $this->headScript()->appendFile('vendor/flot/excanvas.min.js', null, ['conditional' => 'IE']);
    $this->headScript()->appendFile('vendor/flot/jquery.flot.min.js');
    $this->headScript()->appendFile('vendor/flot/jquery.flot.resize.min.js');
    $this->headScript()->appendFile('vendor/flot/jquery.flot.selection.min.js');
    $this->headScript()->appendFile('pubdate_vis.js'); ?>

    <? foreach ($visFacets as $facetField=>$facetRange): ?>
      <div class='authorbox'>
        <div id='datevis<?=$this->escapeHtml($facetField)?>xWrapper' class='hidden'>
          <div id='datevis<?=$facetField ?>x' class='datevis'></div>
        </div>
      </div>
    <? endforeach; ?>
    <div id='dateVisColorSettings'><!-- do not delete! used for passing CSS to Javascript --></div>

    <script>
      $('#dateVisModal').on('show.bs.modal', function (event) {
        <?="
          loadVis('" . $this->recommend->getFacetFields() . "', '"
            . $this->recommend->getSearchParams() . "', VuFind.getPath(), "
            . $this->recommend->getZooming() . ");
          "?>
      });
    </script>
  <? endif; ?>
