<script>
  // @TODO nechapu proc ale kdyz je to pouze v doc.ready tak to po prvnim vyhledavani prestane fungovat

  $( '.list-group' ).on('click', '.arrow', function( event ) {
        event.preventDefault();
        var classArrow = event.target.closest('li').id;
        console.log(classArrow);
        $('#ul-'+classArrow).toggleClass("hide");
    });
</script>

<?
  // @TODO str_replace(' ', '', ) dat vsude kde je id
  function createSub($data, $search, $title, $label, $start, $settings, $stat, $level) {
    // @TODO podle configu facety rozbalit
    $faceId = "ul-".$label."-".str_replace("/",'-',$search);
    $visib = ($stat)?'':'hide';
    if ($label == 'Conspectus') {
      $faceId = str_replace('.', '', $faceId);
      $faceId = str_replace(',', '', $faceId);
      $faceId = str_replace(' ', '', $faceId);
    }
    $html = "<ul id='".$faceId."' class='".$visib."'>";
    $under = "";
    $nonnull = false;

    foreach($data as  $key => $facet) {
      if ($facet['value'] == $facet['displayText'] && strpos($title, "institution"))
        continue;
      if ($key < $start)
        continue;
      $subfacet = "";
      if (strpos(substr($facet['value'], 1), substr($search, 1)) === 0) {// pokud je to podradna faceta...
        if ((int)$facet['value'][0] == ((int)$search[0]) + 1) {// pokud je to faceta o 1 uroven pod ni
          if ($facet['count'] > 0) {
            $nonnull = true;
            $level++;
            $subfacet = createSub($data, $facet['value'], $title, $label, $key, $settings, $facet['isApplied'], $level);
            //$stat = false;
          }
        }
      }
      // @TODO hlidat aji jestli facet['count'] > 0
      if (!empty($subfacet) and $nonnull) {
        $dataValue = "~".$title.":\"".$facet['value']."\"";//'~cpk_detected_format_facet_str_mv:"1/OTHER/PERSON/"'
        $link = createLink($dataValue); // @TODO vytvorit link na facetu pro odkazovani do noveho tabu
        $facetId = $label."-".str_replace("/",'-',$facet['value']);
        if ($label == 'Conspectus') {
          $facetId = str_replace('.', '', $facetId);
          $facetId = str_replace(',', '', $facetId);
          $facetId = str_replace(' ', '', $facetId);
        }
        $under .= "<li class='' id='".$facetId."'>";
        if ($subfacet != "SSXASWWEW")
          $under .= "<b class='arrow'></b>";
        if ($stat || (substr_count($subfacet,"full-active") == substr_count($subfacet,"list-group-item") and substr_count($subfacet,"full-active") != 0)) {
          $under .= orFacet($facet, $dataValue, $link, $level, " full-active");
          // @TODO dat vsem podfacetam full-active
        } else if (substr_count($subfacet,"full-active") > 0)
          $under .= orFacet($facet,$dataValue, $link, $level, " half-active");
        else
          $under .= orFacet($facet,$dataValue, $link, $level, "");
        if ($settings['count']) {
          $under .= "<b class='badge'>" . $facet['count'] . "</b>";
        }
        $under .= "</a>";
        if ($subfacet != "SSXASWWEW")
          $under .= $subfacet;
        $under .= "</li>";
      }
    }

    if (!empty($under))
      return $html.$under."</ul>";
    else
      return "SSXASWWEW";
  }

  function orFacet($facet, $dataValue, $link, $level, $status) {
    $html = "";
    $active = "";
    if ($facet['isApplied'] || $status == " full-active")
      $active = ' full-active active';
    elseif ($status == ' half-active')
      $active = ' half-active';
    // @TODO dat do url pro pripad rozkliknuti do noveho tabu
    $html .= "<a class='list-group-item or-facet facet-filter".$active."' data-parent='".$level."' data-facet='".$dataValue."' href='".$link."'>";
    // @TODO je k necemu to data-parent>
    $html .= "<span class='item'>". $facet['displayText']."</span>";
    return $html;
  }

// @TODO buildQueryString tak tim vytvaret link... vzit pole zakliknutych + sort atd... k tomu pridat facetu u ktere to vytvarime a hodit to te funkce ivrati mi to link
  function createLink($value) {
    $url = $value;
    return "";
  }

?>


<?
$results = $this->recommend->getResults();

$extraFilters = isset($this->extraSideFacetFilters) ? $this->extraSideFacetFilters : array();
$queryParams = $results->getUrlQuery()->getParamArray();
unset($queryParams['filter']);
$i = '?';
$removeFilterUrl = '/Search/Results';
foreach ($queryParams as $key => $value) {
  if (is_array($value)) {
    $value = $value[0];
    $key .= "[]";
  }
  $removeFilterUrl .= $i . $key . '=' . urlencode($value);
  if ($i === '?') {
    $i = '&';
  }
}
// get facets which show in LI or CI and libraries
$facetSettings = $this->recommend->facetSettings();
?>
<!-- hlavni nadpis facet hledani BEGIN -->
<? if ($results->getResultTotal() > 0): ?>
  <h3 class='side-facets-header facets-questionmark-help'>
    <?= $this->transEsc(isset($this->overrideSideFacetCaption) ? $this->overrideSideFacetCaption : 'Narrow Search') ?>
    <?= ($this->librarySearch)? ('adr-facets') : ($filterClass)? $this->help()->getQuestionMarkHelp('ci-facets') : $this->help()->getQuestionMarkHelp('facets') ;?>
  </h3>
<? endif; ?>
<!-- hlavni nadpis facet hledani END -->
<? $filterList = array_merge($results->getParams()->getFilterList(true), $extraFilters); ?>
<!-- vypis filtr BEGIN -->
<? if (!empty($filterList)): ?>
  <div class="list-group filters">
    <? foreach ($filterList as $field => $filters): ?>
      <? foreach ($filters as $i => $filter): ?>
        <?= $filter['displayText'].'<br>'; ?>
      <? endforeach; ?>
    <? endforeach; ?>
    <div class='text-center'>
      <a id='remove-all-filters-async' href='<?=$removeFilterUrl?>'><div class="btn btn-primary btn-sm"><?=$this->transEsc('Remove Filters')?></div></a>
    </div>
  </div>
<? endif; ?>
<!-- vypis filtr END -->
<!-- toto nevim co je BEGIN -->
<div class="checkboxFilter<?if($shown == 0):?> hidden<? endif; ?>">
  <div id="side-panel-eds-filters">
    <?= "asssss" //$html?>
  </div>
</div>
<!-- toto nevim co je END -->

<?= isset($this->sideFacetExtraControls) ? $this->sideFacetExtraControls : '' ?>
<?
$sideFacetSet = $this->recommend->getFacetSet();
$rangeFacets = $this->recommend->getAllRangeFacets();
// @TODO u EDS tak vybi t nejvrhnejsi filter jak jsou 3 moznosti...
?>
<? if (!empty($sideFacetSet) && $results->getResultTotal() > 0) {
  $i = 0;
  foreach ($sideFacetSet as $title => $cluster) {
    // @TODO EDS upravit config... stejne tak i library  -_- jelikoz je spatne tak nefunguje ani jedno z toho
    if (in_array($cluster['label'], ($this->layout()->headerType != "newlibraries") ? $facetSettings['allFieldsSection'] : $facetSettings['librariesSection'])) {
      // @TODO k institucim pridat ty kokotiny jako nejblizzsi ulozit nacist atd...
      //var_dump($cluster);

      if (($cluster['label'] == 'adv_search_year')) {
        // @TODO prepsat casovou osu
        include_once 'SideFacets/PublishDate.phtml';
        continue;
      }
      //var_dump($cluster['list']);
      // @TODO zkontroluje vzdy prvni zaznam a podle toho si vybere co pak bude delat
      $pole = array(
          "count" => false
      );

      $settings = array(
          "count" => true
      );
      $data = $cluster['list'];
      $or = ($cluster['list']['0']['operator'] == 'OR');
      $hierarchical = ($cluster['list'][0]['value'][0] == "0");
      $label = str_replace(' ','',$cluster['label']);

      // =====================
      // BEGIN ciste kvuli oboru, opravuji display text u oboru
      // ====================
      foreach($data as  $key => $facet) {
        if ($cluster['label'] == 'Conspectus') {
          $kokot = $data[$key]['displayText'];
          $new = 0;
          $old = 0;
          while ($new < strlen($kokot)-1) {
            $old = $new+1;
            $new = strpos($kokot, '/', $old);
          }
          $kokot = substr($kokot, $old, $new-$old);
          $data[$key]['displayText'] = $kokot;
        }
      }
      // =====================
      // END
      // ====================

      $html1 = "";
      $html1 .= "<div class='col-xs-12 list-group' id='side-panel-".$label."'>";
      ?>
      <div class="loader loader-hide">
        <div>
          <i class="fa fa-2x fa-refresh fa-spin"></i>
        </div>
      </div><?
      $html1 .= "<li class='arrow list-group-item title' id='facet-".$label."'><span class='arrow-title'>".$this->translate($label)."</span></li>";

      $newhtml = '';
      foreach($data as  $key => $facet) {
        $html = "";
        $subfacet = "";
        $dataValue = (($or)?"~":'').$title.":\"".$facet['value']."\"";//'~cpk_detected_format_facet_str_mv:"1/OTHER/PERSON/"'
        $link = createLink($dataValue);
        $facetId = $label."-".str_replace("/",'-',$facet['value']);
        if ($label == 'Conspectus') {
          $facetId = str_replace('.', '', $facetId);
          $facetId = str_replace(',', '', $facetId);
          $facetId = str_replace(' ', '', $facetId);
        }
        if (! $or || (int)$facet['value'][0] === 0) // vleze jeli and nebo hierarchicka... kdyz je orova ale nehier tak ne
          $html .= "<li class='list-group-item' id='".$facetId."'>";
        if ($or) {
          if ((int)$facet['value'][0] === 0) {
            if ($hierarchical) {
              $subfacet = createSub($data, $facet['value'], $title, $label, $key, $settings, $facet['isApplied'], 0);
              if ($subfacet != "SSXASWWEW")
                $html .= "<b class='arrow'></b>";
            }
            $active = "";
            if (substr_count($subfacet,"full-active") == substr_count($subfacet,"list-group-item") and substr_count($subfacet,"full-active") != 0) {
              $html .= orFacet($facet, $dataValue, $link, 0, " full-active");
              // @TODO dat vsem podfacetam full-active
            } else if (substr_count($subfacet,"full-active") > 0)
              $html .= orFacet($facet,$dataValue, $link, 0, " half-active");
            else
              $html .= orFacet($facet,$dataValue, $link, 0, "");
          }
        }
        // @TODO nakonec to vyresit tak ze vsechno se bude vytvaret na jednom miste a jen pomoci promennych budu vypisovat ruzne tridy nebo nejakou cast uplne vynecham
        if (! $or || (int)$facet['value'][0] === 0) {
          if (! $or) {
            $active = ($facet['isApplied']?' full-active active':'');
            $dataValue = ' data-facet=\''.$dataValue.'\'';
            $html .= "<a href=\"\" class='and-facet facet-filter facetAND".$active."' $dataValue><span>" . $facet['displayText'] . "</span>";
          }
          if ($settings['count']) {
            $html .= "<b class='badge'>" . $facet['count'] . "</b>";
          }
          $html .= "</a>";
          if ($subfacet != "SSXASWWEW")
            $html .= $subfacet;
          $html .= "</li>";
        }
        $newhtml .= $html;
      }
      // @TODO nebo neni urceno v configu
      $schovat = (strpos($newhtml, ' active'))? '': ' hide';
      $html1 .= "<ul id='ul-facet-".$label."' class='".$schovat."'>";
      $html1 .= $newhtml;
      $html1 .= "</ul>";
      $html1 .= "</div>";

      echo $html1;
    }
  }
}
?>





<?=$this->render("Recommend/SideFacets/timelineModal.phtml")?>

<?=$this->render("Recommend/SideFacets/saveTheseInstitutionsConfirmationModal.phtml")?>

<?php

 /**
     * Turn an array into a properly URL-encoded query string.  This is
     * equivalent to the built-in PHP http_build_query function, but it handles
     * arrays in a more compact way and ensures that ampersands don't get
     * messed up based on server-specific settings.
     *
     * @param array $a      Array of parameters to turn into a GET string
     * @param bool  $escape Should we escape the string for use in the view?
     *
     * @return string
     */
    function buildQueryString($a, $escape = true)
    {
        $parts = [];
        foreach ($a as $key => $value) {
            if (is_array($value)) {
                foreach ($value as $current) {
                    $parts[] = urlencode($key . '[]') . '=' . urlencode($current);
                }
            } else {
                $parts[] = urlencode($key) . '=' . urlencode($value);
            }
        }
        $retVal = implode('&', $parts);
        return $escape ? htmlspecialchars($retVal) : $retVal;
    }


?>

