<script>
    // @TODO nechapu proc ale kdyz je to pouze v doc.ready tak to po prvnim vyhledavani prestane fungovat
    $( '.list-group' ).on('click', '.arrow', function( event ) {
        event.preventDefault();
        var classArrow = event.target.closest('li').id;
        console.log(classArrow);
        $('#ul-'+classArrow).toggleClass("hide");
    });
</script>

<?
    $facetFilter = $data;

  if (empty($facetFilter)) {
      $facetFilter['local_institution_facet_str_mv'] = $local_institution_facet_str_mv;
      $facetFilter['cpk_detected_format_facet_str_mv'] = $cpk_detected_format_facet_str_mv;
      $facetFilter['local_statuses_facet_str_mv'] = $local_statuses_facet_str_mv;
      //$facetFilter['subject_facet_str_mv'] = $subject_facet_str_mv;
      //$facetFilter['source_title_facet_str'] = $source_title_facet_str;
      $facetFilter['conspectus_str_mv'] = $conspectus_str_mv;
      //$facetFilter['publisher_str_mv'] = $publisher_str_mv;
      $facetFilter['author_facet_str_mv'] = $author_facet_str_mv;
      $facetFilter['language'] = $language;
      $facetFilter['publishDate'] = $publishDate;
      //$facetFilter['genre_facet_str_mv'] = $genre_facet_str_mv;
      $facetFilter['country_str_mv'] = $country_str_mv;
  }

  /*foreach ($facetFilter as $fac) {
    var_dump($fac);
  }*/
?>
  <!-- hlavni nadpis facet hledani BEGIN -->
  <h3 class='side-facets-header facets-questionmark-help'>
      <?= $this->transEsc(isset($this->overrideSideFacetCaption) ? $this->overrideSideFacetCaption : 'Narrow Search') ?>
      <?= ($this->librarySearch)? ('adr-facets') : ($filterClass)? $this->help()->getQuestionMarkHelp('ci-facets') : $this->help()->getQuestionMarkHelp('facets') ;?>
  </h3>
  <!-- hlavni nadpis facet hledani END -->

<? // TODO udelat vypis filtru?>
<? // $filterList = array_merge($results->getParams()->getFilterList(true), $extraFilters); ?>
  <!-- vypis filtr BEGIN -->
<?if (!empty($filterList)): ?>
  <div class="list-group filters">
      <? foreach ($filterList as $field => $filters): ?>
          <? foreach ($filters as $i => $filter): ?>
              <?= $filter['displayText'].'<br>'; ?>
          <? endforeach; ?>
      <? endforeach; ?>
    <div class='text-center'>
      <a id='remove-all-filters-async' href='<? //=$removeFilterUrl?>'><div class="btn btn-primary btn-sm"><?=$this->transEsc('Remove Filters')?></div></a>
    </div>
  </div>
<? endif; ?>
  <!-- vypis filtr END -->
<? foreach ($facetFilter as $key => $filter) {?>
  <div id="side-panel-<?=$filter['label']?>" class="col-xs-12 list-group">
    <li class="arrow list-group-item title" id="facet-<?=$filter['label']?>">
      <span class="arrow-title">
          <?=$this->transEsc($filter['display'])?>
      </span>
    </li>
    <ul id="ul-facet-<?=$filter['label']?>" class="<?=(!$filter['show'])? 'hide': ''?>">
        <?
        if ($filter['label'] == 'adv_search_year') {
            //include_once 'SideFacets/PublishDate.phtml';
            echo '</ul></div>';
            continue;
        }
        $more = false;
        ?>
        <? foreach ($filter['list'] as $facet) { //echo $facet['value']?>
          <li class="list-group-item <?=(!$facet['show']? 'hide' : '')?>" id="facet-<?=str_replace(':', '', $facet['name'])?>">
              <?=($facet['children'])? '<b class="arrow"></b>' : ''?>
            <a href="<?=$facet['link']?>" class="facet-filter <?=($facet['operator'] == "OR")? 'list-group-item or-facet' : 'and-facet facetAND'?> <?=($facet['actived'] != 0)? ($facet['seq'] == $facet['actived'])? 'active full-active' : 'half-active' : ''?> <?=($facet['fullActive'])? 'active full-active' : ''?>" data-facet='<?=$facet['dataFacet']?>'>
            <span class="<?=($facet['operator'] == "OR")? 'item' : ''?>">
              <?=($facet['bold'])? '<b>' : '';?>
              <?=$facet['displayText']?>
              <?=($facet['bold'])? '</b>' : '';?>
            </span>
              <b class="badge"><?=(!is_null($facet['count'])) ? $facet['count'] : ''?></b>
            </a>

          <?if ($facet['children']) {?>
            <ul id="ul-facet-<?=str_replace(':', '', $facet['name'])?>" class="<?=(!$facet['open'] && !$facet['fullActive'] && !$facet['actived'])? 'hide': ''?>"></ul>
          <?}?>
          <? if ($facet['parent'] != $filter['label']) { ?>
            <script>
                $('#ul-facet-<?=str_replace(':', '', $facet['parent'])?>').append($('#facet-<?=str_replace(':', '', $facet['name'])?>'));
                $('#facet-<?=str_replace(':', '', $facet['name'])?>').append($('#ul-facet-<?=str_replace(':', '', $facet['name'])?>'));
            </script>
        <? }?>
          </li>
        <?
        $moreF = ($facet['value'] == $filter['more'] && !$more)? '<span id="more-facet-'.str_replace(':', '', $facet['name']).'" class="show-all-facets narrow-toggle">'.$this->transEsc("More options").'</span>' : '';
        echo $moreF;
        if (!empty($moreF)) $more = true;
        } ?>
      <?=(!empty($more))? '<span id="less-'.$filter['label'].'" class="hide hide-some-facets narrow-toggle">'.$this->transEsc("less").'</span>' : ''?>
    </ul>

  </div>
<? } ?>
