<script>
    // @TODO nechapu proc ale kdyz je to pouze v doc.ready tak to po prvnim vyhledavani prestane fungovat
    // pokud to tu neni tak po asynchron nefunguje
    $( '.list-group' ).on('click', '.arrow', function( event ) {
        event.preventDefault();
        var classArrow = event.target.closest('li').id;
        console.log(classArrow);
        $('#ul-'+classArrow).toggleClass("hide");
    });

    function escapeHtml(unsafe) {
        return unsafe
            .replace(/&/g, "&amp;")
            .replace(/</g, "&lt;")
            .replace(/>/g, "&gt;")
            .replace(/"/g, "&quot;")
            .replace(/'/g, "&#039;");
    }
</script>

<?
$facetFilter = $data;
?>
<!-- hlavni nadpis facet hledani BEGIN -->
<h3 class='side-facets-header facets-questionmark-help'>
    <?= $this->transEsc(isset($this->overrideSideFacetCaption) ? $this->overrideSideFacetCaption : 'Narrow Search') ?>
</h3>
<!-- hlavni nadpis facet hledani END -->

<? // $filterList = array_merge($results->getParams()->getFilterList(true), $extraFilters); ?>
<!-- vypis filtr BEGIN -->
<?if (!empty($usedFilter)): ?>
    <? //var_dump($usedFilter); ?>
    <? $filterList = $usedFilter; ?>
  <div class="list-group filters">
      <? foreach ($filterList as $field => $filters): ?>

        <ul style="padding: 0; cursor: pointer;">
            <? foreach ($filters as $i => $filter): ?>
              <li class="active activedF" data-facet='<?=$filter['dataFacet']?>' style="padding-left: <?=($i > 0)? '20px' : '0px'?>;"><?=($i <= 0)?$this->transEsc($field) . ': ': ''?><b  style="color: grey; display: inline-block; width: <?=($i > 0)? '30px' : '0px'?>; font-weight: normal; font-size: 12px;"><?=($i > 0)? $filter['operator']: ''?></b>
                <a><?= $filter['display']; ?></a></li>
            <? endforeach; ?>
        </ul>
      <? endforeach; ?>
    <div class='text-center'>
      <a id='remove-all-filters-async' href='<? //=$removeFilterUrl?>'><div class="btn btn-primary btn-sm"><?=$this->transEsc('Remove Filters')?></div></a>
    </div>
  </div>
<? endif; ?>
<!-- vypis filtr END -->

<?
/*
    $filterTranslations = [
        'eds_limiter_FT'        => 'find_fulltext_documents_only',
        'eds_limiter_RV'        => 'find_reviewed_documents_only',
        'eds_expander_fulltext' => 'serach_also_fulltexts_of_documents',
    ];
  $html = '';
  $shown = 0;
  foreach ($checkboxFilters as $current) {
    $html .= '<label class="checkbox';
    if($results->getResultTotal() < 1 && !$current['selected'] && !$current['alwaysVisible']) {
      $html .= ' hidden';
    } else {
      $shown ++;
    }
    $html .= '"><input type="checkbox" class="jsTreeLikeCheckbox" name="filter[]" value="'.$this->escapeHtmlAttr($current['filter']).'"
      '. ($current['selected'] ? 'checked="checked"' : '') .' id="'.$this->escapeHtmlAttr(str_replace(' ', '', $current['desc'])).'"/>';
    $html .= '<span class="jsTreeLikeCheckboxDescription">'.$this->translate($filterTranslations[$current['desc']]).'</span>';
    $html .= '</label>';
  }
*/
?>

<div class="checkboxFilter <?=(!empty($_GET['database']) && $_GET['database'] == "EDS")? '' : 'hidden'?>">
  <div id="side-panel-eds-filters">
    <label class="checkbox"><input type="checkbox" class="jsTreeLikeCheckbox" name="filter[]" value="LIMIT!FT:y"
                                   id="eds_limiter_FT"><span class="jsTreeLikeCheckboxDescription">Vyhledej pouze dokumenty s existujícím plným textem</span></label><label
        class="checkbox"><input type="checkbox" class="jsTreeLikeCheckbox" name="filter[]" value="LIMIT!RV:y"
                                id="eds_limiter_RV"><span class="jsTreeLikeCheckboxDescription">Vyhledej pouze recenzované dokumenty</span></label><label
        class="checkbox"><input type="checkbox" class="jsTreeLikeCheckbox" name="filter[]" value="EXPAND:fulltext"
                                id="eds_expander_fulltext"><span class="jsTreeLikeCheckboxDescription">Prohledej i plné texty dokumentů</span></label>
  </div>
</div>
<? foreach ($facetFilter as $key => $filter) {?>
  <div id="side-panel-<?=$filter['encoded']?>" class="col-xs-12 list-group">
    <li class="arrow list-group-item title" id="facet-<?=$filter['encoded']?>">
      <span class="arrow-title">
          <?=$this->transEsc($filter['display'])?>
      </span>
    </li>
    <ul id="ul-facet-<?=$filter['encoded']?>" class="<?=(!$filter['show'])? 'hide': ''?>">

      <!-- vypis instituce icons nerest,favorite... BEGIN -->
        <? //if($filter['display'] == 'Institution'): ?>
        <? if(0): ?>
          <div class='col-xs-5 col-sm-12 col-lg-5 institutions-loaders'>
              <? if($this->auth()->isLoggedIn()): ?>
                <a href='#' title='<?=$this->translate('Load preferred institutions')?>' data-toggle="tooltip" id='load-saved-institutions'>
                  <i class='pr-web-uploadarrow'> </i>
                </a>
              <? endif; ?>

            <? // FIXME data se musi ziskat uz v Results a jen je predat pres controller sem?>
              <? if ($this->recommend instanceof \CPK\Recommend\SideFacets && isset($myLibs) && is_array($myLibs) && count($myLibs) > 0):
                  $urlParams = $results->getUrlQuery()->getParamArray();
                  $newParams = array('type' => 'AllFields');
                  $filtered = array();
                  if (isset($urlParams['filter'])) {
                      $decompressedFilters = explode("|", \LZCompressor\LZString::decompressFromBase64(specialUrlDecode($urlParams['filter'])));
                      foreach ($decompressedFilters as $param) {
                          if (strpos($param, '~institution:') === 0) {
                              continue;
                          }
                          $filtered[] = $param;
                      }
                  }
                  $newParams = $urlParams;
                  $newParams['filter'] = $filtered;
                  $firstLib = true;
                  $myLibraries = '';
                  foreach ($myLibs as $myLib) {
                      $myLibraries .= $this->recommend->getInstutitionMapping($myLib).';';
                  }
                  $myLibraries = substr($myLibraries, 0, -1);
                  echo "<div class='hidden' id='my-libraries-container'>$myLibraries</div>";
                  ?>
                <a href='#' title='<?=$this->translate('Load my institutions')?>' data-toggle="tooltip" id='load-my-institutions'>
                  <i class='pr-interface-househome2'> </i>
                </a>
              <? endif; ?>

            <a href='#' title='<?=$this->translate('Load nearest institutions')?>' data-toggle="tooltip" id='load-nearest-institutions'>
              <i class='pr-location-pinmap5'> </i>
            </a>
          </div>
        <? endif; ?>
      <!-- vypis instituce icons nerest,favorite... END -->




        <?
        if ($filter['label'] == 'adv_search_year') {
            //include_once 'SideFacets/PublishDate.phtml';
            echo '</ul></div>';
            continue;
        }
        $more = false;
        ?>
        <? foreach ($filter['list'] as $facet) { //echo $facet['value']?>
          <li class="list-group-item <?=(!$facet['show']? 'hide' : '')?>" id="facet-<?=$facet['name']?>">
              <?=($facet['children'])? '<b class="arrow"></b>' : ''?>
            <a href='<?=$facet['link']?>' class="facet-filter <?=($facet['operator'] == "OR")? 'list-group-item or-facet' : 'and-facet facetAND'?> <?=($facet['actived'] != 0)? ($facet['seq'] == $facet['actived'])? 'active full-active' : 'half-active' : ''?> <?=($facet['fullActive'])? 'active full-active' : ''?>" data-facet='<?=str_replace("'", "&#039;", $facet['dataFacet'])?>'>
              <script>
                  var el = document.getElementById('facet-<?=$facet['name']?>');
                  var moje = window.location.href;
                  moje = moje.substr(0, (moje.indexOf('&filter') !== -1)? moje.indexOf('&filter') : moje.length);
                  var nove = ('<?= $facet['link']?>'  !== "")? "&filter%5B%5D=" + specialUrlEncode(LZString.compressToBase64('<?=$facet['link']?>')) : '';
                  var link = moje + nove;
                  el.getElementsByClassName('facet-filter')[0].href = link;
              </script>
            <span class="<?=($facet['operator'] == "OR")? 'item' : ''?>">
              <?=($facet['bold'])? '<b>' : '';?>
              <?=$facet['displayText']?>
              <?=($facet['bold'])? '</b>' : '';?>
            </span>
              <b class="badge"><?=(!is_null($facet['count'])) ? $facet['count'] : ''?></b>
            </a>

              <?if ($facet['children']) {?>
                <ul id="ul-facet-<?=$facet['name']?>" class="<?=(!$facet['open'] && !$facet['fullActive'] && !$facet['actived'])? 'hide': ''?>"></ul>
              <?}?>
              <? if ($facet['parent'] != $filter['encoded']) { ?>
                <script>
                    $('#ul-facet-<?=$facet['parent']?>').append($('#facet-<?=$facet['name']?>'));
                    $('#facet-<?=$facet['name']?>').append($('#ul-facet-<?=$facet['name']?>'));
                </script>
              <? }?>
          </li>
            <?
            $moreF = ($facet['value'] == $filter['more'] && !$more)? '<span id="more-facet-'.$facet['name'].'" class="show-all-facets narrow-toggle">'.$this->transEsc("More options").'</span>' : '';
            echo $moreF;
            if (!empty($moreF)) $more = true;
        } ?>
        <?=(!empty($more))? '<span id="less-'.$filter['encoded'].'" class="hide hide-some-facets narrow-toggle">'.$this->transEsc("less").'</span>' : ''?>
    </ul>
  </div>
<? } ?>
