<table>
  <tbody>
    <? foreach ($idps as $idp): ?>
      <tr class='link idp-record' data-ng-click="fedLoginCtrl.login('<?=htmlentities(json_encode($idp))?>')">
        <td class='col-sm-3'>
          <? if ($idp['logo']): ?>
            <img height='30' src='<?=$idp['logo']?>' alt='<?=$idp['name']?>'>
          <? endif; ?>
        </td>
        <td>
          <a href='<?=$idp['href']?>' title='<?=$idp['name']?>'>
            <?=$idp['name']?>
          </a>
        </td>
      </tr>
    <? endforeach; ?>
  </tbody>
</table>