<table id="table-regular_identity_providers">
  <tbody>
  <?php foreach($idps as $idp) : $json = json_encode($idp);?>
    <tr class="link idp-record" data-identityProvider="<?=htmlentities($json)?>">
      <td class="col-sm-3">
        <?php if ($idp['logo']) : ?>
          <img height="30" src="<?=$idp['logo']?>">
        <?php endif;?>
      </td>
      <td><a href="<?=$idp['href']?>"><?=$idp['name']?></a></td>
    </tr>
  <? endforeach; ?>
  </tbody>
</table>