<?php
/**
 * Login Modal Dialog.
 *
 * @global boolean $user
 */


if ( $user === true ) {
  return '';
}

$portalPage = $this->portalPages()->getPage('moznosti-prihlaseni-a-registrace', explode("-", $this->layout()->userLang)[0]);

?><div class="modal fade" id="loginModal" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><?=$this->translate('login_last_used')?></h4>
            </div>
            <div class="modal-body last-idps" id="last-identity-providers"></div>
            <div id="login-help-link" class="modal-header link" style="cursor: pointer">
                <h4 class="modal-title"><?=$portalPage['title']?></h4>
            </div>
            <div id="login-help-content" class="modal-body" hidden="hidden">
                <?=$portalPage['content'] ?>
            </div>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><?=$this->translate('login_with')?></h4>
            </div>
            <div class="modal-body">
                <?=$this->render('login/identity-providers.phtml', [
                    'idps' => $this->identityProviders()->getLibraries()
                ]) ?>
            </div>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><?=$this->translate('login_other')?></h4>
            </div>
            <div class="modal-body">
                <?=$this->render('login/identity-providers.phtml', [
                    'idps' => $this->identityProviders()->getOthers()
                ]) ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"><?=$this->translate('close')?></button>
            </div>
        </div>
    </div>
</div>
